# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Bufi(object):
    def setupUi(self, Bufi):
        Bufi.setObjectName("Bufi")
        Bufi.resize(600, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Bufi.sizePolicy().hasHeightForWidth())
        Bufi.setSizePolicy(sizePolicy)
        Bufi.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(Bufi)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.tab)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modules_dropdown = QtWidgets.QComboBox(self.verticalWidget)
        self.modules_dropdown.setObjectName("modules_dropdown")
        self.modules_dropdown.addItem("")
        self.verticalLayout_2.addWidget(self.modules_dropdown)
        self.search_input = QtWidgets.QLineEdit(self.verticalWidget)
        self.search_input.setObjectName("search_input")
        self.verticalLayout_2.addWidget(self.search_input)
        self.repositories_list = QtWidgets.QListWidget(self.verticalWidget)
        self.repositories_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.repositories_list.setObjectName("repositories_list")
        self.verticalLayout_2.addWidget(self.repositories_list)
        self.action_buttons_layout = QtWidgets.QHBoxLayout()
        self.action_buttons_layout.setObjectName("action_buttons_layout")
        self.new_repository_button = QtWidgets.QPushButton(self.verticalWidget)
        self.new_repository_button.setEnabled(False)
        self.new_repository_button.setObjectName("new_repository_button")
        self.action_buttons_layout.addWidget(self.new_repository_button)
        self.delete_repository_button = QtWidgets.QPushButton(self.verticalWidget)
        self.delete_repository_button.setEnabled(False)
        self.delete_repository_button.setObjectName("delete_repository_button")
        self.action_buttons_layout.addWidget(self.delete_repository_button)
        self.verticalLayout_2.addLayout(self.action_buttons_layout)
        self.horizontalLayout_3.addWidget(self.verticalWidget)
        self.repository_info_widget = QtWidgets.QWidget(self.tab)
        self.repository_info_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repository_info_widget.sizePolicy().hasHeightForWidth())
        self.repository_info_widget.setSizePolicy(sizePolicy)
        self.repository_info_widget.setMinimumSize(QtCore.QSize(280, 0))
        self.repository_info_widget.setObjectName("repository_info_widget")
        self.repository_info_layout = QtWidgets.QVBoxLayout(self.repository_info_widget)
        self.repository_info_layout.setObjectName("repository_info_layout")
        self.repository_name_label = QtWidgets.QLabel(self.repository_info_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.repository_name_label.setFont(font)
        self.repository_name_label.setTextFormat(QtCore.Qt.AutoText)
        self.repository_name_label.setObjectName("repository_name_label")
        self.repository_info_layout.addWidget(self.repository_name_label)
        self.repository_properties_form = QtWidgets.QWidget(self.repository_info_widget)
        self.repository_properties_form.setObjectName("repository_properties_form")
        self.repository_info_form = QtWidgets.QFormLayout(self.repository_properties_form)
        self.repository_info_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.repository_info_form.setObjectName("repository_info_form")
        self.created_on_label = QtWidgets.QLabel(self.repository_properties_form)
        self.created_on_label.setEnabled(True)
        self.created_on_label.setTextFormat(QtCore.Qt.AutoText)
        self.created_on_label.setWordWrap(False)
        self.created_on_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.created_on_label.setObjectName("created_on_label")
        self.repository_info_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.created_on_label)
        self.info_created_on_label = QtWidgets.QLabel(self.repository_properties_form)
        self.info_created_on_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_created_on_label.setText("")
        self.info_created_on_label.setObjectName("info_created_on_label")
        self.repository_info_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.info_created_on_label)
        self.label_2 = QtWidgets.QLabel(self.repository_properties_form)
        self.label_2.setObjectName("label_2")
        self.repository_info_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.info_description_label = QtWidgets.QLabel(self.repository_properties_form)
        self.info_description_label.setText("")
        self.info_description_label.setObjectName("info_description_label")
        self.repository_info_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.info_description_label)
        self.label_3 = QtWidgets.QLabel(self.repository_properties_form)
        self.label_3.setObjectName("label_3")
        self.repository_info_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.info_type_label = QtWidgets.QLabel(self.repository_properties_form)
        self.info_type_label.setText("")
        self.info_type_label.setObjectName("info_type_label")
        self.repository_info_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.info_type_label)
        self.repository_info_layout.addWidget(self.repository_properties_form)
        self.label_5 = QtWidgets.QLabel(self.repository_info_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.repository_info_layout.addWidget(self.label_5)
        self.acl_table = QtWidgets.QTableWidget(self.repository_info_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acl_table.sizePolicy().hasHeightForWidth())
        self.acl_table.setSizePolicy(sizePolicy)
        self.acl_table.setStyleSheet("")
        self.acl_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.acl_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.acl_table.setAlternatingRowColors(True)
        self.acl_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.acl_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.acl_table.setShowGrid(False)
        self.acl_table.setWordWrap(False)
        self.acl_table.setCornerButtonEnabled(False)
        self.acl_table.setColumnCount(2)
        self.acl_table.setObjectName("acl_table")
        self.acl_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.acl_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.acl_table.setHorizontalHeaderItem(1, item)
        self.acl_table.horizontalHeader().setVisible(False)
        self.acl_table.horizontalHeader().setCascadingSectionResizes(True)
        self.acl_table.verticalHeader().setVisible(False)
        self.acl_table.verticalHeader().setCascadingSectionResizes(False)
        self.repository_info_layout.addWidget(self.acl_table)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.add_acl_button = QtWidgets.QPushButton(self.repository_info_widget)
        self.add_acl_button.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.add_acl_button.setFont(font)
        self.add_acl_button.setObjectName("add_acl_button")
        self.horizontalLayout_8.addWidget(self.add_acl_button)
        self.remove_acl_button = QtWidgets.QPushButton(self.repository_info_widget)
        self.remove_acl_button.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.remove_acl_button.setFont(font)
        self.remove_acl_button.setObjectName("remove_acl_button")
        self.horizontalLayout_8.addWidget(self.remove_acl_button)
        self.edit_acl_button = QtWidgets.QPushButton(self.repository_info_widget)
        self.edit_acl_button.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edit_acl_button.setFont(font)
        self.edit_acl_button.setObjectName("edit_acl_button")
        self.horizontalLayout_8.addWidget(self.edit_acl_button)
        self.repository_info_layout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3.addWidget(self.repository_info_widget)
        self.repository_info_widget.raise_()
        self.verticalWidget.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ssh_keys_list = QtWidgets.QListWidget(self.tab_2)
        self.ssh_keys_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ssh_keys_list.setObjectName("ssh_keys_list")
        self.verticalLayout_3.addWidget(self.ssh_keys_list)
        self.horizontalWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.new_ssh_key_button = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.new_ssh_key_button.setFont(font)
        self.new_ssh_key_button.setObjectName("new_ssh_key_button")
        self.horizontalLayout_5.addWidget(self.new_ssh_key_button)
        self.delete_ssh_key_button = QtWidgets.QPushButton(self.horizontalWidget)
        self.delete_ssh_key_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.delete_ssh_key_button.setFont(font)
        self.delete_ssh_key_button.setObjectName("delete_ssh_key_button")
        self.horizontalLayout_5.addWidget(self.delete_ssh_key_button)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.ssh_key_info = QtWidgets.QWidget(self.tab_2)
        self.ssh_key_info.setEnabled(False)
        self.ssh_key_info.setObjectName("ssh_key_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ssh_key_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.ssh_key_info)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.ssh_key_info)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ssh_info_owner_label = QtWidgets.QLabel(self.ssh_key_info)
        self.ssh_info_owner_label.setText("")
        self.ssh_info_owner_label.setObjectName("ssh_info_owner_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ssh_info_owner_label)
        self.label_6 = QtWidgets.QLabel(self.ssh_key_info)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.ssh_info_type_label = QtWidgets.QLabel(self.ssh_key_info)
        self.ssh_info_type_label.setText("")
        self.ssh_info_type_label.setObjectName("ssh_info_type_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ssh_info_type_label)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.label_8 = QtWidgets.QLabel(self.ssh_key_info)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.key_contents_text = QtWidgets.QPlainTextEdit(self.ssh_key_info)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.key_contents_text.setFont(font)
        self.key_contents_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.key_contents_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.key_contents_text.setUndoRedoEnabled(False)
        self.key_contents_text.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.key_contents_text.setPlainText("")
        self.key_contents_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.key_contents_text.setObjectName("key_contents_text")
        self.verticalLayout_4.addWidget(self.key_contents_text)
        self.horizontalLayout_4.addWidget(self.ssh_key_info)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_name_label = QtWidgets.QLabel(self.centralwidget)
        self.user_name_label.setText("")
        self.user_name_label.setObjectName("user_name_label")
        self.horizontalLayout.addWidget(self.user_name_label)
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_button.sizePolicy().hasHeightForWidth())
        self.logout_button.setSizePolicy(sizePolicy)
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout.addWidget(self.logout_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Bufi.setCentralWidget(self.centralwidget)

        self.retranslateUi(Bufi)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Bufi)

    def retranslateUi(self, Bufi):
        _translate = QtCore.QCoreApplication.translate
        Bufi.setWindowTitle(_translate("Bufi", "BUFI"))
        self.modules_dropdown.setItemText(0, _translate("Bufi", "All modules"))
        self.search_input.setPlaceholderText(_translate("Bufi", "Search..."))
        self.new_repository_button.setText(_translate("Bufi", "New..."))
        self.delete_repository_button.setText(_translate("Bufi", "Delete"))
        self.repository_name_label.setText(_translate("Bufi", "No repository selected"))
        self.created_on_label.setText(_translate("Bufi", "Created on"))
        self.label_2.setText(_translate("Bufi", "Description"))
        self.label_3.setText(_translate("Bufi", "Type"))
        self.label_5.setText(_translate("Bufi", "ACL"))
        self.acl_table.setSortingEnabled(True)
        item = self.acl_table.horizontalHeaderItem(0)
        item.setText(_translate("Bufi", "user_name"))
        item = self.acl_table.horizontalHeaderItem(1)
        item.setText(_translate("Bufi", "acl"))
        self.add_acl_button.setText(_translate("Bufi", "+"))
        self.remove_acl_button.setText(_translate("Bufi", "-"))
        self.edit_acl_button.setText(_translate("Bufi", "🖉"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Bufi", "Repositories"))
        self.new_ssh_key_button.setText(_translate("Bufi", "+"))
        self.delete_ssh_key_button.setText(_translate("Bufi", "-"))
        self.label_7.setText(_translate("Bufi", "Key info"))
        self.label_4.setText(_translate("Bufi", "Owner"))
        self.label_6.setText(_translate("Bufi", "Type"))
        self.label_8.setText(_translate("Bufi", "Key contents"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Bufi", "SSH keys"))
        self.logout_button.setText(_translate("Bufi", "Log out"))

